- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes
- name: start nginx
  service:
      name: nginx
      state: started
  become: yes
- name: copy the nginx config file and restart nginx
  copy:
    src:  "{{ config_file }}" 
    dest: /etc/nginx/sites-available/
  become: yes
- name: create symlink
  file:
    src: "/etc/nginx/sites-available/{{ config_file }}"
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
