#================================= Paths ======================================

path.data: ${NOMAD_TASK_DIR}/data

path.logs: ${NOMAD_TASK_DIR}/logs

#=========================== Filebeat inputs =============================

filebeat.inputs:

- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - ${NOMAD_ALLOC_DIR}/logs/api-gateway-task*

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Kafka output ------------------------------
output.kafka:
  enabled: true
  hosts: ["localhost:9092"]
  version: '1.0.0'
  topic: "api-gateway-filebeat"
  partition.hash:
    reachable_only: true
  compression: gzip
  max_message_bytes: 1000000
  required_acks: 1

