- name: check wrk home folder stat
  stat: path={{ wrk_home }}
  register: wrk_home_stat

- name: git clone wrk
  git: 
    repo: "{{ wrk_git_repo }}"
    dest: "{{ wrk_home }}"
  register: wrk_was_downloaded
  when: wrk_home_stat.stat.exists == False
  tags: [wrk]

- name: check wrk stat
  stat: path={{ wrk_home }}/wrk
  register: wrk__stat

- name: build wrk
  shell: "cd {{ wrk_home }} && make clean && make "
  when: wrk__stat.stat.exists == False
  tags: [wrk]

- name: copy the nginx config file and restart nginx
  copy:
    src:  "{{ wrk_post_script }}" 
    dest: "{{ wrk_home }}/scripts" 
  tags: [wrk]
